#%RAML 1.0 Library

usage: Global traits for the CEDSCI API

traits:
  orderable: !include orderable.raml
  pageable: !include pageable.raml
  sortable: !include sortable.raml
  contentCacheable: !include content-cacheable.raml
  partial: !include partial.raml
  globalParameters: !include global-parameters.raml
