#%RAML 1.0 DataType

properties:
  listId:
    type: string
    required: true
  mapId:
    type: string
    required: true
  sourceTableId:
    type: string
    required: true
  program:
    type: string
    required: true
  vintage:
    type: array
    required: true
  geography:
    type: array
    required: true
  accessURI:
    type: string
    required: true
type: object
example: !include ../examples/map.json
