#%RAML 1.0 DataType

type: object
displayName: Map List
description: This type provides a list of map results.
properties:
  resultCount: number
  results:
    type: array
    items:
      type: !include map.raml
  moreItems: string
type: object
example: !include ../examples/maps.json
