#%RAML 1.0 DataType

type: object
displayName: Page List
description: This type provides a list of webpage results.
properties:
  resultCount: number
  results:
    type: array
    items:
      type: !include page.raml
  moreItems: string
type: object
example: !include ../examples/pages.json
